Feature/adicionando exercicios list1
rafaelkeiti/neuron-exercices pull request #1
Opened 2023-03-24 04:28 UTC by rafaelkeiti

2023-03-25 23:40 UTC, Caiuzu requested changes

2023-03-25 23:40 UTC, Caiuzu commented on List-1/src/exercice_03.java
> +        double number1 = 0;
Não utilizar alfanuméricos em nome de variavel utilize por exemplo: firstNumber, firstValue

2023-03-25 23:40 UTC, Caiuzu commented on List-1/src/exercice_06.java
> +        area = 3.14 * Math.pow(ray, 2);
para valores constantes como 3.14' criar uma constante da seguinte maneira:

public static final Double PI_VALUE = 3.14; // nomes de constantes sempre em snakecase em capslock (separado por _ )

2023-03-25 23:40 UTC, Caiuzu commented on List-1/src/exercice_07.java
> +        result = (base * height) * 2;
2 vira constante

2023-03-25 23:40 UTC, Caiuzu commented on List-1/src/exercice_09.java
> +        result = 5 * ((FahrenheitTemperature - 32) / 9);
5, 32 e 9 viram constantes

2023-03-25 23:40 UTC, Caiuzu commented on List-1/src/exercice_11.java
> +        result = (number1 * 2) * (number2 / 2);
constantes

2023-03-25 23:40 UTC, Caiuzu commented on List-1/src/exercice_12.java
> +        double IdealWeight = 0;
variavel sempre em camelcase, iniciando com a primeira letra minuscula, -> idealWeight

2023-03-25 23:40 UTC, Caiuzu commented on List-1/src/exercice_13.java
> +        } else if (Objects.equals(sex, "f") || Objects.equals(sex, "F")) {
"f", "F", "m", "M" constante

2023-03-25 23:40 UTC, Caiuzu commented on List-1/src/exercice_15.java
> +        double earningsPerHour = 0, salaryTotal = 0, incomeTax = 0, inss = 0, syndicate = 0, netSalary = 0;
quebrar os valores por linha

2023-03-25 23:40 UTC, Caiuzu commented on List-1/src/exercice_15.java
> +        inss = (salaryTotal - incomeTax) * 0.08;
constante 0.11, 0.08 , etc

2023-04-02 22:21 UTC, Caiuzu requested changes

2023-04-02 22:21 UTC, Caiuzu commented on List-1/src/exercice_05.java
> +    public static final int METER_VALUE_IN_CM = 100;
quando uma constante não está sendo utilizada em outra classe, podemos deixar como private

private static final int METER_VALUE_IN_CM = 100;

2023-04-02 22:21 UTC, Caiuzu commented on List-1/src/exercice_02.java
> +        double typedNumber;
pode colocar o double typedNumber; no meido do código, sem precisar inicializar no topo, como

```java
  double typedNumber = input.nextDouble();
```

2023-04-02 22:26 UTC, OberdanSoldi requested changes

2023-04-02 22:26 UTC, OberdanSoldi commented on List-1/src/exercice_02.java
> +        typedNumber = input.nextDouble();
pode ser feito da seguinte maneira:

```java
double typedNumber = input.nextDouble(); 
```

2023-04-02 22:26 UTC, OberdanSoldi commented on List-1/src/exercice_03.java
> +        firstNumber = input.nextDouble();
pode ser feito da seguinte maneira:

```java
double firstNumber = input.nextDouble();
```

```java
double secondNumber = input.nextDouble();
```

```java
double totalSum = firstNumber + secondNumber;
```

2023-04-02 22:36 UTC, Caiuzu requested changes

2023-04-02 22:36 UTC, Caiuzu commented on List-1/src/exercice_09.java
> +        int FahrenheitTemperature;
variável sempre inicia com letra minuscula

2023-04-02 22:36 UTC, Caiuzu commented on List-1/src/exercice_17.java
> +        resultLiterCan18 = (int) Math.ceil(resultMetroSquare / EIGHTEEN_LITER_CANS);
Não usar alfanuméricos nas variáveis

2023-04-20 02:57 UTC, Caiuzu approved these changes
LGTM

2023-04-20 03:34 UTC, merged