Feature/adicionando exercicios list2
rafaelkeiti/neuron-exercices pull request #2
Opened 2023-03-31 01:28 UTC by rafaelkeiti

2023-04-02 22:08 UTC, OberdanSoldi commented on List-2/src/exercice_04.java
> +import java.util.Scanner;
Da pra fazer usando os métodos toLowerCase ou toUpperCase, ai não precisa criar uma string com "aeiouAEIOU"

2023-04-02 22:18 UTC, OberdanSoldi requested changes

2023-04-02 22:18 UTC, OberdanSoldi commented on List-2/src/exercice_04.java
> +
Da pra fazer usando os métodos toLowerCase ou toUpperCase, ai não precisa criar uma string com "aeiouAEIOU"

2023-04-20 03:02 UTC, Caiuzu requested changes

2023-04-20 04:02 UTC, Caiuzu approved these changes
LGTM

2023-04-20 04:02 UTC, merged